config/routes.rb
Rails.application.routes.draw do
  # ルート
  #=======================
  root 'static_pages#home'

  # StaticPages
  #=======================
  get '/tos',            to: 'static_pages#tos'

  # Users
  #=======================
  resources :users do
    member do
      get :following, :followers
    end
  end
  get  '/signup',   to: 'users#new'
  post '/signup',   to: 'users#create'
  get  '/users/:id/edit_password',  to: 'users#edit_password', 
                                    as: 'edit_password'
  patch '/users/:id/edit_password', to: 'users#update_password'

  # Sessions
  #=======================
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete 'logout',  to: 'sessions#destroy'

  # PasswordResets
  #=======================
  resources :password_resets,  only: %i[new create edit update]

  # Microposts
  #=======================
  resources :microposts, only: %i[new create destroy show]

  # Relationships
  #=======================
  resources :relationships, only: %i[create destroy]

  # Comments
  #=======================
  resources :comments,  only: %i[create destroy]

  # Likes
  #=======================
  resources :likes,  only: %i[create destroy]

  # Search_items
  #=======================
  get '/search/:id',        to: 'search_items#show', as: 'search_item'
  resources :search_items, only: %i[create]

  # Facebook
  #=======================
  get '/auth/facebook/callback',  to: 'sessions#facebook',
                                  as: 'facebook_auth_callback'

  # Notifications
  #=======================
  resources :notifications, only: %i[index]
end

app/models/notification.rb
class Notification < ApplicationRecord
  # 関連
  #=======================
  belongs_to :sender,    class_name: 'User'
  belongs_to :receiver,  class_name: 'User'

  # バリデーション
  #=======================
  default_scope -> { order(created_at: :desc) }
  validates :sender_id,         presence: true
  validates :receiver_id,       presence: true
  validates :m_name,            presence: true
  validates :r_id,              presence: true

  # 特異メソッド
  #=======================
  class << self
    # confirmedをtrue(確認済)にする
    def update_confirmed_to_true(receiver)
      where(receiver_id: receiver.id).find_each do |notification|
        notification.update(confirmed: true)
      end
    end
  end

  # インスタンスメソッド
  #=======================

  # コメント,お気に入りから投稿を取得する
  def get_micropost
    model_name = m_name
    model_name.constantize.find_by(id: r_id).micropost
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  # Before
  #=======================
  # ログイン済フィルタ
  before_action :logged_in_user, only: %i[index]
  # ログイン中ユーザのユーザ名
  before_action :full_current_user_name, only: %i[index]

  # After
  #=======================
  # indexページを開いた時点で確認済とする
  after_action  :update_confirmed_to_true

  # Action
  #=======================
  def index
    @notifications = current_user.receive_notifications
                                 .paginate(page: params[:page], per_page: 15)
  end

  # private
  #=======================
  private

  def update_confirmed_to_true
    # Notice:
    # current_user.receive_notificationsからupdate_allを実行すると
    # デッドロックが発生するため、逐次処理で更新する
    Notification.update_confirmed_to_true(current_user)
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  # 通知表示のためのメッセージを返す
  def get_notification_message(notification)
    model_name = notification.m_name
    case model_name
    when Relationship.to_s
      'あなたをフォローしました'
    when Comment.to_s
      'あなたの投稿にコメントをしました'
    when Like.to_s
      'あなたの投稿をお気に入りにしました'
    end
  end

  # 通知件数が100件以上の場合は、99+と表示させる
  def notification_count_limit(count)
    if count > 99
      '99+'
    else
      count.to_s
    end
  end
end

app/views/notifications/_header_menu_norification.html.erb
<% if current_user.new_notifications? %>
  <% cls = 'new-notification-exist' %>
<% else %>
  <% cls = nil %>
<% end %>
<div class="inline-block">
  <%= link_to notifications_path, class: 'nav-link' do%>
    <span class="align-top">新着</span>
    <span class="text-center align-top new-notification-counter <%= cls %>">
      <%= notification_count_limit(current_user.new_notifications_count) %>
    </span>
  <% end %>
</div>

app/views/notifications/_notification.html.erb
<% cls = notification.confirmed? ? nil : 'new-notification' %>
<div class="card card-body <%= cls %>">
  <div class="inline-block">
    <%= gravatar_for(notification.sender, size: 30) %>
    <%= link_to user_path(notification.sender), class: 'context' do %>
    <%= "#{notification.sender.full_name}@#{notification.sender.user_name}" %>
    <% end %>
    <span>が</span>
  </div>
  <span><%= get_notification_message(notification) %></span>
  <% unless notification.m_name == 'Relationship' %>
    <%= link_to '確認する', micropost_path(notification.get_micropost), class: 'context' %>
  <% end %>
</div>

app/views/notifications/index.html.erb
<% provide(:title, '通知一覧') %>
<%= render 'shared/header' %>
<div class="container-fluid">
  <div class="row justify-content-center notification-index-row">
      <div class="col-md-7">
        <%= render @notifications %>
        <%= render 'shared/will_pagination', objects: @notifications %>
      </div>
  </div>
</div>
<script type="text/javascript">
  $(function(){
    // bootstrap-will_paginateがBootstrap4.0以降に未対応のため、
    // 対応するクラスを追加
    $(".pagination li").addClass("page-item");
    $(".pagination a").addClass("page-link");
  });
</script>