config/routes.rb
Rails.application.routes.draw do
  # ルート
  #=======================
  root 'static_pages#home'

  # StaticPages
  #=======================
  get '/tos',            to: 'static_pages#tos'

  # Users
  #=======================
  resources :users do
    member do
      get :following, :followers
    end
  end
  get  '/signup',   to: 'users#new'
  post '/signup',   to: 'users#create'
  get  '/users/:id/edit_password',  to: 'users#edit_password', 
                                    as: 'edit_password'
  patch '/users/:id/edit_password', to: 'users#update_password'

  # Sessions
  #=======================
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete 'logout',  to: 'sessions#destroy'

  # PasswordResets
  #=======================
  resources :password_resets,  only: %i[new create edit update]

  # Microposts
  #=======================
  resources :microposts, only: %i[new create destroy show]

  # Relationships
  #=======================
  resources :relationships, only: %i[create destroy]

  # Comments
  #=======================
  resources :comments,  only: %i[create destroy]

  # Likes
  #=======================
  resources :likes,  only: %i[create destroy]

  # Search_items
  #=======================
  get '/search/:id',        to: 'search_items#show', as: 'search_item'
  resources :search_items, only: %i[create]

  # Facebook
  #=======================
  get '/auth/facebook/callback',  to: 'sessions#facebook',
                                  as: 'facebook_auth_callback'

  # Notifications
  #=======================
  resources :notifications, only: %i[index]
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <p>入力内容に誤りがあります</p>
    <ol>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ol>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash.any? %>
  <% flash.each do |type, msg| %>
    <div class="alert alert-<%= type %> flash-message" id="flash">
      <button type="button" class="close" data-dismiss="alert" aria-label="閉じる">
        <span style="background-color: transparent;" aria-hidden="true">&times;</span>
      </button>
      <%= msg %>
    </div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="row justify-content-center border-top footer-row">
    <% if login? %>
      <%= link_to '写真を投稿する', new_micropost_path %>
    <% end %>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <%= link_to root_path do %>
      <%= image_tag("logo.png", alt: "logo", class: "header-logo") %>
    <% end %>
    <button type="button" class="navbar-toggler" data-toggle="collapse" 
            data-target="#header" aria-controls="navbarNav"
            aria-expanded="false" aria-label="ナビゲーションの切替">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="header">
      <ul class="navbar-nav ml-auto">
        <% if login? %>
        <%# ログイン時に表示するメニュー %>
        <li class="nav-item">
          <%= render 'notifications/header_menu_norification' %>
        </li>
        <li class="nav-item nav-link">
          <%= render 'search_items/search_form' %>
        </li>
        <li class="nav-item">
          <%= link_to @disp_name, user_path(current_user), class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link' %>
        </li>
        <% else %>
         <%# 非ログイン時に表示するメニュー %>
         <li class="nav-item">
           <%= link_to 'サインアップ', signup_path, class: 'nav-link' %>
         </li>
         <li class="nav-item">
           <%= link_to 'ログイン', login_path, class: 'nav-link' %>
         </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_stat.html.erb
<div class="col-md-3">
  <%= link_to user_path(@user) do %>
    <span class="context">投稿 <%= @user.microposts.count %>件
  <% end %>
</div>
<div class="col-md-4">
  <%= link_to followers_user_path(@user), remote: true do %>
    <span id="followers" class="context">フォロワ <%= @user.followers.count %>人</span>
  <% end %>
</div>
<div class="col-md-5">
  <%= link_to following_user_path(@user), remote: true do %>
    <span id="following" class="context">フォロー <%= @user.following.count %>人</span>
  <% end %>
</div>

app/views/shared/_will_pagination.html.erb
<div class="row justify-content-center">
  <% if objects.any? %>
    <%= will_paginate objects, previous_label: '前へ', next_label: '次へ' %>
  <% end %>
</div>